trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: Cache@2  # Not required, but Qodana will open projects with cache faster.
  inputs:
    key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
    path: '$(Agent.TempDirectory)/qodana/cache'
    restoreKeys: |
      "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
      "$(Build.Repository.Name)"
- task: QodanaScan@2025
  env:
    QODANA_TOKEN: $(QODANA_TOKEN)
    QODANA_ENDPOINT: 'https://qodana.cloud'
- task: UseDotNet@2
  inputs:
    version: '9.x'
    packageType: 'sdk'
- script: |
    dotnet restore
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build project'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(builderConfiguration) --output $(Builder.ArtifactStagingDirectory)'
    zipAfterPublish: true
  displayName: 'Publish project'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifacts'
