services:
  api:
    image: ${PRIVATE_REGISTRY_IMAGENAME}:latest
    ports:
      - "${HOST_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DATABASE_CONNECTION_STRING}
      - Jwt__Key=${JWT_KEY}